Making changes to Get-All_Sections_and _Memberships.ps1 to have ExchangeOnlineManagement
OfficeDev/O365-EDU-Tools pull request #100
Opened 2022-04-13 11:41 UTC by mohankrishnaseelam

Making changes to Get-All_Sections_and _Memberships.ps1 to have ExchangeOnlineManagement

### Related Issue
[_Please put the related issue number to reference if applicable_  ](https://dev.azure.com/1edu/DIP%20Master/_workitems/edit/132835)

### Summary
Modified to have ExchangeOnlineManagement module

### Reason
_Why is this change being proposed?_

### Proposed Change(s)
- change 1
- change 2
- change N

### Details
_Detailed description of the change(s)_

### Additional Info
_Any additional information or context_

### References
[Example](www.microsoft.com)

### Checklist
- [ ] Documentation

2022-04-13 13:32 UTC, AyronJohnson commented on SDS Scripts/Get-All_Sections_and_Memberships.ps1
> +
Add Connect-ExchangeOnline

2022-04-13 13:37 UTC, AyronJohnson commented on SDS Scripts/Get-All_Sections_and_Memberships.ps1
> +    After you complete the login in the web browser, the session in the Powershell 7 window is authenticated via the regular Azure AD authentication flow, and the Exchange Online cmdlets are imported
-Device not necessary.  Remove PowerShell 7 and just leave PowerShell as this should be able to run in prior versions and hopefully some future ones.

2022-04-18 12:21 UTC, mohankrishnaseelam commented on SDS Scripts/Get-All_Sections_and_Memberships.ps1
> +
As suggested updated the code.

2022-04-18 12:21 UTC, mohankrishnaseelam commented on SDS Scripts/Get-All_Sections_and_Memberships.ps1
> +    After you complete the login in the web browser, the session in the Powershell 7 window is authenticated via the regular Azure AD authentication flow, and the Exchange Online cmdlets are imported
As suggested updated the comment.

2022-04-18 14:46 UTC, AyronJohnson requested changes
Just noticed that the group owner column is listing System.Object.  I think this is because there are multiple owners.  Can we list multiple?

2022-04-19 13:37 UTC, merged

2022-04-19 13:38 UTC, AyronJohnson approved these changes