Created a script to restore AnchorID to SDS V1 format
OfficeDev/O365-EDU-Tools pull request #102
Opened 2022-04-22 09:05 UTC by tejakoppa

Created a script to restore AnchorID to SDS V1 format

2022-04-22 16:28 UTC, AyronJohnson commented on SDS Scripts/Restore-V1_AnchorID_Attributes.ps1
> +        write-output $users | Export-Csv -Path "$csvfilePath" -NoTypeInformation
Error when exporting to csv when no users found.  Please allow script to output to prompt when no users were found and exit instead of throwing error.

2022-04-22 16:31 UTC, AyronJohnson requested changes
See comment about error.  Also my log file has weird chinese characters.

2022-04-25 15:07 UTC, tejakoppa commented on SDS Scripts/Restore-V1_AnchorID_Attributes.ps1
> +        write-output $users | Export-Csv -Path "$csvfilePath" -NoTypeInformation
Fixed it.

2022-04-25 15:39 UTC, AyronJohnson commented on SDS Scripts/Restore-V1_AnchorID_Attributes.ps1
> +}
Error encoutered if no file is created.  Maybe add an else condition if no $users, then write to console that no users are found and exit script

2022-04-25 16:26 UTC, tejakoppa commented on SDS Scripts/Restore-V1_AnchorID_Attributes.ps1
> +}
Fixed it.

2022-04-27 13:09 UTC, closed without merging