OR to SDS ADF Template
OfficeDev/O365-EDU-Tools pull request #132
Opened 2024-11-07 15:13 UTC by bramchandram

Created OR to SDS ADF template. The file name is 'OR_to_SDS_ADF_Template.json'.
The file is available under the OR folder. Please let me know if you face any issues finding the file.

And please review it and let me know the required changes.

2024-11-07 15:30 UTC, bramchandram commented
> @bramchandram please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

2024-11-11 14:36 UTC, AyronJohnson requested changes
Please fix first round of review

2024-11-21 02:10 UTC, AyronJohnson commented on CustomSolutions/SDS_ADF_ETL_Integrations/Canvas/README.md
> +# Solution Guide: Canvas API Provisiong Reports Data extract and Upload to SDS
This is the instructions for Canvas.  Please make the changes from the previous OneRoster document.

2024-11-21 02:43 UTC, AyronJohnson requested changes

2024-11-21 02:43 UTC, AyronJohnson commented on CustomSolutions/SDS_ADF_ETL_Integrations/OR/OR_to_SDS_ADF_Template.Json
> +            "defaultValue": "https://partnertest.infinitecampus.org/campus/oneroster/microsofttest/ims/oneroster/v1p1"
A url should not be present here.

2024-11-21 02:43 UTC, AyronJohnson commented on CustomSolutions/SDS_ADF_ETL_Integrations/OR/OR_to_SDS_ADF_Template.Json
> +                                            "referenceName": "Transform_to_Optionals_SDS_csv",
NIT: Remove "s" from all instances of "Optionals"

2024-11-21 02:43 UTC, AyronJohnson commented on CustomSolutions/SDS_ADF_ETL_Integrations/Canvas/README.md
> +# Solution Guide: Canvas API Provisiong Reports Data extract and Upload to SDS
This is the instructions for Canvas. Please remove and convert the pdf from the previous OneRoster document to markdown.

2024-12-04 16:42 UTC, AyronJohnson commented
@bramchandram please see review comments.  Also, I saw the corrections below are needed in addition.  Thanks

- line 313 AppName not showing because it is a tag.  Need to escape
- lines 125, 128 replace SMS with LMS?
- line 130 remove line break tag
- line 136 replace sentence with  "Once the ADF and storage accounts are created under stonerostersds, create a container named as refcodes to import refCodes.csv used for subject in classes."

2024-12-19 14:04 UTC, AyronJohnson requested changes

2024-12-19 14:04 UTC, AyronJohnson commented on CustomSolutions/SDS_ADF_ETL_Integrations/OR/OneRoster_README.md
> +| entraAppClientId                 | string   | The clientId for the app registration. Found at Azure Active Directory -> App registrations <br/>-> \<AppName>\ -> Overview -> Application (client) ID
The backslash \ is appearing after the >.  Please move.

2024-12-19 14:04 UTC, AyronJohnson commented on CustomSolutions/SDS_ADF_ETL_Integrations/OR/OneRoster_README.md
> +Once the ADF and storage accounts are created under stonerostersds, create a container named as refcodes to import refCodes.csv used for subject in classes.
Remove "as" after the word "named"

2024-12-23 14:05 UTC, AyronJohnson approved these changes

2024-12-23 14:06 UTC, merged