Sds scripts bts2021
OfficeDev/O365-EDU-Tools pull request #65
Opened 2021-06-15 14:26 UTC by AyronJohnson

Priority SDS scripts requested for bts 2021.  Modified Get-All_SDS_Attributes.ps1 to use Graph API.  Also added new scripts Remove-SchoolAU_Memberships.ps1, Remove-SchoolSG_Memberships.ps1, SDS Scripts/Update-AnchorID_Attributes.ps1

2021-07-09 19:55 UTC, Mson888 requested changes

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Get-All_SDS_Attributes.ps1
> +$lastRefreshed = $null
same comment as the other pack  -- ie. try to pass in / return the token, lastreferesh instead of mainpulating the global variable directly

also consider moving this to a common.ps1 and then import it in... update the instructions that one needs to download the common.ps1 in addition to this ps1... 

This will save time for folks in the future and have just one place for Refresh-Token, installs. etc.

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Get-All_SDS_Attributes.ps1
> +    $i = 1
more descriptive counter name?

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Get-All_SDS_Attributes.ps1
> +    while (($currentUrl -ne $null) -and ($i -ile 4999)) {
why only get 4999 pages?..

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Remove-SchoolAU_Memberships.ps1
> +function Initialize() {
yea.. lets put these common functions in a common.ps1 and load it in

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Remove-SchoolAU_Memberships.ps1
> +    $i = 0 #counter for progress
NIT: put this closer to where it is getting used (ie. near the foreach)

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Remove-SchoolAU_Memberships.ps1
> +    Write-Host "`nTarget both students and teachers in SDS school created AUs (yes/no)?.  Default: students only" -ForegroundColor White
what the determination on some logs going to a log file and some going to console?..  (ie. why isn't everything going to the log file)

as well- why mix write-host and write-output .. would be good to stay consistent until absolutely needed

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Remove-SchoolAU_Memberships.ps1
> +
NIT: remove extra line?

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +    $results = $schoolSGMemberships -ne "Welcome To Microsoft Graph!"
curious why  $schoolSGMemvership would ever equal the string here..  isnt it an array?

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +            $index++
$index doesn't seem useful here - we are not doing anything with it? .. meant to log?

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +            $removeUrl = 'https://graph.microsoft.com/beta/groups/' + $grpm.SGObjectId + '/members/' + $grpm.SGMemberObjectId +'/$ref'
consider batch API -- this will be ALOT of network I/O if done one at a time...

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +            $removeUrl = 'https://graph.microsoft.com/beta/groups/' + $grpm.SGObjectId + '/members/' + $grpm.SGMemberObjectId +'/$ref'
consider : make the baseurl configurable (ie. ppe vs. prod) - so we can use these in test land too?
(non blocking)

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +        Foreach ($grpm in $grpMemberList)
this might take hours to do ... should we have a access token refresh check periodically?

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +            Write-Output "[$index/$grpMemberCount] Removing SG Member id [$($grpm.SGMemberObjectId)] of `"$($grpm.SGDisplayName)`" [$($grpm.SGObjectId)] from directory"
might want to pipe this out to a file?..  this can easily have thousands of rows (ie in teh school AU case for example)

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +                    #$userUri = "https://graph.microsoft.com/beta/users/" + $grpMember.Id + "?$grpMemberSelectClause"
why comment out?

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Update-AnchorID_Attributes.ps1
> +            #removing the anchor id
NIT: fix spacing/tabbing

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Update-AnchorID_Attributes.ps1
> +			$index++
index not used?.. remove?

(general comment) - open up notepad++ or something and convert all tabs to spaces.... then make sure things are space correclty throughout all the files please )

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Update-AnchorID_Attributes.ps1
> +        foreach ($user in $users)
NIT: fix tabbing/spacing

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Update-AnchorID_Attributes.ps1
> +        write-output $users | Export-Csv -Path "$csvfilePath" -NoTypeInformation
curious - does this work well if we have to dump out 20K users (Or 200K users or 1M).

I wonder if we need to dump out/append every 'n users' instead of doing this all or nothing

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Update-AnchorID_Attributes.ps1
> +            # $graphRequest = invoke-graphrequest -Method PATCH -Uri $updateUrl -Body '{"extension_fe2174665583431c953114ff7268b7b3_Education_AnchorId": null}'
why comenting out?

2021-07-09 19:55 UTC, Mson888 commented on SDS Scripts/Get-All_SDS_Attributes.ps1
>  Change Log:
In general:
- refactor common methods to a common.ps1
- avoid using global vars - pass in, pass out values (especially around when to establish need to refresh token)
- consider having this work for PPE and PROD (this now seems to only work for PROD)
- fix indent / spaces

will re-review once current batch of comments are addressed

2021-07-14 06:02 UTC, acherrymsft commented on SDS Scripts/Get-All_SDS_Attributes.ps1
>  Change Log:
@Mson888 : Having a common helper makes deployment harder ("download these two files and put them in the same directory" versus "download and run this file").

I agree about the global vars. For PPE vs. PROD -- AAD PPE/PROD, or SDS PPE/PROD?

2021-07-14 21:28 UTC, AyronJohnson commented on SDS Scripts/Update-AnchorID_Attributes.ps1
> +            # $graphRequest = invoke-graphrequest -Method PATCH -Uri $updateUrl -Body '{"extension_fe2174665583431c953114ff7268b7b3_Education_AnchorId": null}'
At the time undecided whether to change the anchor or remove it.  Any preference according to what you know v2.1 works?

2021-07-15 20:00 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes.ps1
>  Change Log:
@Mson888 @acherrymsft I think a lot of the scripts would have to be updated to use the common file.  Shall we keep the functions in their own file until we come to agreement?

2021-07-15 22:41 UTC, Mson888 commented on SDS Scripts/Get-All_SDS_Attributes.ps1
>  Change Log:
i was thinking we would do it for these new ones .. and slowly move over.

I understand downloading 2 files might be hard.. but really?

2021-07-15 22:52 UTC, Mson888 commented on SDS Scripts/Get-All_SDS_Attributes.ps1
>  Change Log:
For PPE / PROD -> AAD PPE .. (these scripts should be agnostic of SDS PPE/PROD) since they talk to AAD directly for the most part

2021-07-16 14:19 UTC, AyronJohnson commented on SDS Scripts/Update-AnchorID_Attributes.ps1
> +			$index++
using index a few lines above

`Write-Output "[$index/$userCount] Updating attribute [$($user.userAnchorId)] from user `"$($user.userDisplayName)`" "
`

2021-07-16 14:26 UTC, AyronJohnson commented on SDS Scripts/Remove-SchoolAU_Memberships.ps1
> +    $i = 0 #counter for progress
Moving just before loop

2021-07-16 16:50 UTC, AyronJohnson commented on SDS Scripts/Update-AnchorID_Attributes.ps1
> +            #removing the anchor id
will do

2021-07-16 16:58 UTC, AyronJohnson commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +                    #$userUri = "https://graph.microsoft.com/beta/users/" + $grpMember.Id + "?$grpMemberSelectClause"
Was having issues getting user data from endpoint.  Not needed.  Will remove.

2021-07-16 17:58 UTC, Mson888 commented on SDS Scripts/Update-AnchorID_Attributes.ps1
> +			$index++
ah missed it because of the tabbign /spacing

2021-07-16 18:00 UTC, Mson888 commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +            $removeUrl = 'https://graph.microsoft.com/beta/groups/' + $grpm.SGObjectId + '/members/' + $grpm.SGMemberObjectId +'/$ref'
(non blocking)

2021-07-16 18:42 UTC, AyronJohnson commented on SDS Scripts/Update-AnchorID_Attributes.ps1
> +			$index++
No worries.  Thanks the review :)

2021-07-19 16:29 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes.ps1
> +Version 2.0, 04/06/2021 - Change to MS Graph Moddule - Ayron Johnson
corrected

2021-07-19 16:33 UTC, AyronJohnson commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +            $removeUrl = 'https://graph.microsoft.com/beta/groups/' + $grpm.SGObjectId + '/members/' + $grpm.SGMemberObjectId +'/$ref'
I saw the need for this too and updated the scripts

2021-07-19 16:35 UTC, AyronJohnson commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +            $index++
Used to output count of updated objects

2021-07-19 16:59 UTC, AyronJohnson commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +    $results = $schoolSGMemberships -ne "Welcome To Microsoft Graph!"
I think I copied code and overlooked the array part.  Removing the check since message is output when connected to graph anyway.

2021-07-20 15:06 UTC, AyronJohnson commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +        Foreach ($grpm in $grpMemberList)
@Mson888 I am changing to calling PageAll-GraphRequest which calls Refresh-Token instead of just invoke-graphrequest command

2021-07-20 15:20 UTC, AyronJohnson commented on SDS Scripts/Remove-SchoolAU_Memberships.ps1
> +
removing

2021-07-20 15:41 UTC, AyronJohnson commented on SDS Scripts/Remove-SchoolAU_Memberships.ps1
> +    Write-Host "`nTarget both students and teachers in SDS school created AUs (yes/no)?.  Default: students only" -ForegroundColor White
@Mson888 Seems that write-host works better when requesting for input and write-output when logging to a file.  Log file just logging what is done and but also outputting to separate file which contains data for next step in this case removing members.  Will look into where we are not logging.

2021-07-20 15:43 UTC, AyronJohnson commented on SDS Scripts/Remove-SchoolAU_Memberships.ps1
> +function Initialize() {
@Mson888 I am moving these to the common file.  Wondering if a better way would be to reference online file or download it each time so will have the latest.

2021-07-20 17:30 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes.ps1
> +    while (($currentUrl -ne $null) -and ($i -ile 4999)) {
Removing

2021-07-20 17:32 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes.ps1
> +    $i = 1
removing since also removing 4999 page counter

2021-07-20 18:47 UTC, AyronJohnson commented on SDS Scripts/Update-AnchorID_Attributes.ps1
> +            # $graphRequest = invoke-graphrequest -Method PATCH -Uri $updateUrl -Body '{"extension_fe2174665583431c953114ff7268b7b3_Education_AnchorId": null}'
Removing null anchor id per email discussion.

2021-07-20 21:20 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes.ps1
> +$lastRefreshed = $null
Adding this.

2021-07-21 18:38 UTC, AyronJohnson commented on SDS Scripts/Remove-SchoolAU_Memberships.ps1
> +function Initialize() {
Giving option to download latest from gitHub per discussion

2021-07-26 20:31 UTC, AyronJohnson commented on SDS Scripts/Remove-SchoolSG_Memberships.ps1
> +            Write-Output "[$index/$grpMemberCount] Removing SG Member id [$($grpm.SGMemberObjectId)] of `"$($grpm.SGDisplayName)`" [$($grpm.SGObjectId)] from directory"
adding

2021-07-28 18:26 UTC, Mson888 commented on SDS Scripts/common.ps1
> +    $global:nextLink = $response.'@odata.nextLink'
should make a note to address (it's weird for a common method to set global scope vars) - would expect to pass it back out as a value

2021-07-28 18:40 UTC, Mson888 approved these changes

2022-03-08 14:48 UTC, closed without merging