- Added functionality to Refresh access token and Reset guardian for …
OfficeDev/O365-EDU-Tools pull request #66
Opened 2021-06-24 18:13 UTC by dileeshm

- Added functionality to Refresh access token 
- Reset guardian for students mentioned in a csv input file

2021-07-08 23:19 UTC, Mson888 requested changes

2021-07-08 23:19 UTC, Mson888 commented on SDS Scripts/Reset-Guardians.ps1
> -function Add-Guardian($userId, $email, $displayName, $phone, $relationship, $authToken) {
curious why is Add-Guardian removed?

2021-07-08 23:19 UTC, Mson888 commented on SDS Scripts/Reset-Guardians.ps1
> +        Write-Progress -Activity "Getting All SDS synced students"
do we really want this line here?  this is a paged query so will see alot of this spew out (especially with large tenants).

If this is so that we know things are still moving, maybe have smthg like:

 Write-Progress -Activity "Getting All SDS synced students $count"   .. where $count is number of users pulled down thus far by coutning up the $response.value

2021-07-08 23:19 UTC, Mson888 commented on SDS Scripts/Reset-Guardians.ps1
>              Write-Host "Resetting guardians for $($student.displayName), id $($student.id)"
might be out of scope for this change, but this script will probably break down for larger tenants going the 'all students' route

suggest doing some/all of the below:
a) as we get all students, dump out the student ids (so that if we need to replay we just replay the ones that need to be reset) -- instead of going through every student again

b) do the resetting a page at a time (ie. get a page, do the page), then get the next page and so on
(non blocking comment)

2021-07-22 11:55 UTC, dileeshm commented on SDS Scripts/Reset-Guardians.ps1
> -function Add-Guardian($userId, $email, $displayName, $phone, $relationship, $authToken) {
Add-Guardian function is not called from the script anywhere, so I thought better remove it. Do you think we still keep the function?

2021-07-22 11:57 UTC, dileeshm commented on SDS Scripts/Reset-Guardians.ps1
> +    Reset guardian for one student: .\Reset-Guardians.ps1 -OutFolder . -clientId "940e3d66-95aa-41d9-237d-45e961889107" -clientSecret "2cJ]-[p19402Ac;Y+7<b>5b" -tenantDomain "contoso.onmicrosoft.com"
Used the same clientid/secret from the existing script version. I will change them while pushing the new code.

2021-08-04 11:13 UTC, dileeshm commented on SDS Scripts/Reset-Guardians.ps1
> +        Write-Progress -Activity "Getting All SDS synced students"
Write progress was added for testing purpose and forgot to remove. Removed it now.

2021-08-04 11:14 UTC, dileeshm commented on SDS Scripts/Reset-Guardians.ps1
> +    if ($global:authToken -eq $null) {
Removed

2021-08-04 11:16 UTC, dileeshm commented on SDS Scripts/Reset-Guardians.ps1
> +    $global:lastRefreshed = get-date
Modified the script to pass variables instead of using global variables.

2021-08-04 11:38 UTC, dileeshm commented on SDS Scripts/Reset-Guardians.ps1
> +    foreach($studentAadObject in $studentAadObjectIdList) {
Is it like moving below code to a function and call the function from if/elseif blocks? 

foreach($studentAadObjectId in $studentAadObjectIdsArr) {
        Write-Host "Resetting guardians for student object Id $studentAadObjectId"
        Reset-GuardiansForUser -userId $studentAadObjectId -authToken $authToken -lastRefreshed $lastRefreshed
    }

2021-08-04 11:41 UTC, dileeshm commented on SDS Scripts/Reset-Guardians.ps1
>              Write-Host "Resetting guardians for $($student.displayName), id $($student.id)"
Yes, I agree with you on the large tenants case. I will discuss with Wendy and create a new ticket for this change.

2021-08-06 17:05 UTC, merged