Automate creation of Information Barriers based on Tenant AU topology
OfficeDev/O365-EDU-Tools pull request #73
Opened 2021-10-21 15:23 UTC by AyronJohnson

Adding script to create information barriers from SDS created administrative units for each school and All Teachers security group.  Also few bug fixes.

2021-10-29 21:03 UTC, AyronJohnson commented on SDS Scripts/Create-SDS_Information_Barriers.ps1
> +. .\common.ps1
Work item 126776 created to address in future

2021-10-29 21:19 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes.ps1
> +        $data | Export-Csv $filePath -Force -NotypeInformation -ErrorAction SilentlyContinue
removing

2021-10-29 21:32 UTC, AyronJohnson commented on SDS Scripts/Create-SDS_Information_Barriers.ps1
> +        write-output "[$(get-date -Format G)] Retrieve $($allSchoolAUs.Count) school AUs." | out-file $logFilePath -Append
This is outputting how many school au's are found. Should I just remove this?

2021-10-29 21:38 UTC, AyronJohnson commented on SDS Scripts/Create-SDS_Information_Barriers.ps1
> +                write-host $au.displayName
I see your point.  Will add more text.

2021-10-29 21:47 UTC, AyronJohnson commented on SDS Scripts/Create-SDS_Information_Barriers.ps1
> +                    New-OrganizationSegment -Name $au.displayName -UserGroupFilter "AdministrativeUnits -eq '$($au.displayName)'" | Out-Null
@acherrymsft I see your point.  I going off the syntax listed in organization segment documentation which has only the name and no id's.  The way we are finding the school au, I don't think we can get the wrong one in case of duplicate names.

2021-10-29 22:02 UTC, AyronJohnson commented on SDS Scripts/Create-SDS_Information_Barriers.ps1
> +        #write to school SG count to log
Nevermind, I  misread your comment and revised the text

2021-11-01 08:11 UTC, acherrymsft commented on SDS Scripts/Create-SDS_Information_Barriers.ps1
> +        write-output "[$(get-date -Format G)] Retrieve $($allSchoolAUs.Count) school AUs." | out-file $logFilePath -Append
It outputs how many AUs are found in this page, not how many total.

2021-11-01 14:25 UTC, AyronJohnson commented on SDS Scripts/Create-SDS_Information_Barriers.ps1
> +        write-output "[$(get-date -Format G)] Retrieve $($allSchoolAUs.Count) school AUs." | out-file $logFilePath -Append
@acherrymsft Yes you are correct.  I misspoke/typed.  Will add counter for page.

2021-11-02 05:04 UTC, acherrymsft commented on SDS Scripts/Create-SDS_Information_Barriers.ps1
> +                    New-InformationBarrierPolicy -Name "$($au.displayName) - IB" -AssignedSegment $au.displayName -SegmentsAllowed $au.displayName -State Active -Force | Out-Null
Is there a two-step process to minimize? Download everything, save to temp storage, then work from temp storage to actually create the policies?

2021-11-02 05:08 UTC, acherrymsft commented
I'm concerned about failing partially through and the recovery process -- all pages will need to be processed, etc. If this is acceptable, then the change looks good.

2021-11-02 18:49 UTC, AyronJohnson commented on SDS Scripts/Create-SDS_Information_Barriers.ps1
> +                    New-InformationBarrierPolicy -Name "$($au.displayName) - IB" -AssignedSegment $au.displayName -SegmentsAllowed $au.displayName -State Active -Force | Out-Null
@acherrymsft Ok for school aus, I separated the get and create parts into two functions and used a csv file to store and read from

2021-11-05 17:50 UTC, acherrymsft requested changes

2021-11-05 17:50 UTC, acherrymsft commented on SDS Scripts/Create-SDS_Information_Barriers.ps1
> +Get-AllSchoolAUs
The CSV functionality is only helpful if it's possible to resume. Right now, even with a skipToken there is no such capability; if the AU file is already there, it is deleted instead of being used.

2021-11-08 17:48 UTC, AyronJohnson commented on SDS Scripts/Create-SDS_Information_Barriers.ps1
> +Get-AllSchoolAUs
Added another condition for removing csv.

2021-11-09 08:09 UTC, merged