Making Graph API changes
OfficeDev/O365-EDU-Tools pull request #92
Opened 2022-03-23 11:53 UTC by SarathSrestaluri

Making changes to implement Graph API.

2022-03-23 20:39 UTC, AyronJohnson commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +    [switch] $PPE,
Please add optional $graphVersion parameter with default value of beta and include it in endpoints so that user can switch if needed.

2022-03-23 20:43 UTC, AyronJohnson commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +        foreach($groupMember in $groupMembers){
Add new line

2022-03-23 21:07 UTC, AyronJohnson commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +    Write-Output @"
Dev suggesting to remove this fucntion and put verbiage in .NOTES section in the header.  You can use `Get-Help -Name .\<script name>.ps1 -Full | Out-String | Write-Error`
from the catch blocks

2022-03-23 21:09 UTC, AyronJohnson commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +    d. If you are returned to the PowerShell sesion without error, you are correctly set up
session is misspelled

2022-03-23 21:21 UTC, AyronJohnson commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +        Write-Output "Processing Memberships for Group `"$($group.displayName)`" [$($group.Id)] from directory" | out-file $logFilePath -Append
Add something like "id:" before the guid so user knows what it is.  Also, this line seems to be missing a timestamp

2022-03-23 21:41 UTC, AyronJohnson commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +            $AUObj | Add-Member NoteProperty -Name MemberDisplayName -Value $groupMember.displayName
I'm seeing a blank line without members in my output.  This should not display if members are present

2022-03-23 21:44 UTC, AyronJohnson commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
>  Script Name:
NIT: Header is unnecessary.

2022-03-23 21:45 UTC, AyronJohnson requested changes
See inline comments.  General correction is to make sure casing and whitespace is uniform.  Good job.

2022-03-23 21:52 UTC, AyronJohnson commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +        Write-Host -ForegroundColor Green "Exporting data for group $DN"
Write line for each group will fill up screen for large tenants.  Maybe use write-progress with -percentcomplete instead.

2022-04-01 10:52 UTC, SarathSrestaluri commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +    [switch] $PPE,
Added graphVersion parameter

2022-04-01 10:56 UTC, SarathSrestaluri commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +    [string] $OutFolder = ".",
Fixed

2022-04-01 10:56 UTC, SarathSrestaluri commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +        foreach($groupMember in $groupMembers){
Fixed

2022-04-01 10:57 UTC, SarathSrestaluri commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +    mkdir $OutFolder;
Fixed

2022-04-01 10:57 UTC, SarathSrestaluri commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +    Write-Output @"
Removed old function and used get-help

2022-04-01 10:58 UTC, SarathSrestaluri commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +    d. If you are returned to the PowerShell sesion without error, you are correctly set up
fixed

2022-04-01 10:58 UTC, SarathSrestaluri commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +        Write-Output "Processing Memberships for Group `"$($group.displayName)`" [$($group.Id)] from directory" | out-file $logFilePath -Append
fixed

2022-04-01 11:03 UTC, SarathSrestaluri commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +            $AUObj | Add-Member NoteProperty -Name MemberDisplayName -Value $groupMember.displayName
In output some blank lines were coming , to avoid this scenario added if condition with member id check, to skip the blank/null member id records.

2022-04-01 11:03 UTC, SarathSrestaluri commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
>  Script Name:
Removed the header

2022-04-01 11:04 UTC, SarathSrestaluri commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +        Write-Host -ForegroundColor Green "Exporting data for group $DN"
Used write-progress with -percentcomplete

2022-04-01 15:03 UTC, AyronJohnson commented on SDS Scripts/Email Restrictions/Export-Class_Membership_for_Restrictions.ps1
> +        Write-Output "Processing Memberships for Group `"$($group.displayName)`" [$($group.Id)] from directory" | out-file $logFilePath -Append
I meant put a label for the $group.Id in the output but I guess this might be just NIT

2022-04-01 15:05 UTC, AyronJohnson approved these changes

2022-04-01 15:05 UTC, merged