Modified Get-All_Sections_and_Membership_Counts.ps1 script to implement Graph API
OfficeDev/O365-EDU-Tools pull request #93
Opened 2022-03-23 14:31 UTC by tejakoppa

Modified Get-All_Sections_and_Membership_Counts.ps1 script to implement Graph API

2022-03-24 13:27 UTC, AyronJohnson commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
>  Script Name:
NIT: Header not necessary

2022-03-24 14:28 UTC, AyronJohnson commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +    [string] $OutFolder = ".",
- Create a $graphVersion parameter so user can change version if needed, default value, and use the variable in endpoints.  
- Better to create folder to output the files.  
- NIT: Put outfolder in lowercase to make names consistent.

2022-03-24 14:32 UTC, AyronJohnson commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +    d. If you are returned to the PowerShell sesion without error, you are correctly set up
Session is misspelled

2022-03-24 14:41 UTC, AyronJohnson commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +function Get-PrerequisiteHelp {
Dev is suggesting that we remove this function and put text in the .NOTES section of help.  The help can be called in the catch blocks like this `Get-Help -Name .\<filename>.ps1 -Full | Out-String | Write-Error`

2022-03-24 14:42 UTC, AyronJohnson commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +		Write-Output "[$(get-date -Format G)] [$index/$groupCount] Processing Memberships for Group `"$($group.DisplayName)`" [$($group.Id)]`n" | out-file $logFilePath -Append
Maybe put something like id: in front of the group id so user can know what it is.

2022-03-24 14:44 UTC, AyronJohnson commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +	mkdir $OutFolder;
Use `| Out-null` so that output of folder creation is not displayed

2022-03-24 14:54 UTC, AyronJohnson commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +    b. Execute: "connect-graph -scopes GroupMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All, Directory.AccessAsUser.All" to bring up a sign in UI.
NIT: Whitespace at end

2022-03-24 14:57 UTC, AyronJohnson commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +		$graphEndPoint = $GraphEndpointPPE
Double tabbed

2022-03-24 15:03 UTC, AyronJohnson commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +		Write-Output "[$(get-date -Format G)] [$index/$groupCount] Processing Memberships for Group `"$($group.DisplayName)`" [$($group.Id)]`n" | out-file $logFilePath -Append
[/] is appearing in the log.

2022-03-24 15:07 UTC, AyronJohnson requested changes
Script works but needs clean up.  See comments for changes.  Thanks

2022-03-29 15:25 UTC, tejakoppa commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +    [string] $OutFolder = ".",
Created the graphVersion parameter, created the outPut folder and used lowercase to make names consistent

2022-03-29 15:28 UTC, tejakoppa commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +	mkdir $OutFolder;
Updated to use Out-null.

2022-03-29 15:28 UTC, tejakoppa commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +
Fixed it.

2022-03-29 15:29 UTC, tejakoppa commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +		$groupMembersCount = $groupMembers.Count
Updated the spacing to make it readable.

2022-03-29 15:30 UTC, tejakoppa commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +		Write-Output "[$(get-date -Format G)] [$index/$groupCount] Processing Memberships for Group `"$($group.DisplayName)`" [$($group.Id)]`n" | out-file $logFilePath -Append
Fixed it.

2022-03-30 14:21 UTC, AyronJohnson requested changes
@tejakoppa most of the changes are fixed but big issue here is that the script was failing due to a few lines.

2022-03-30 16:38 UTC, tejakoppa commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +. .\common.ps1
Fixed it.

2022-03-30 16:38 UTC, tejakoppa commented on SDS Scripts/Get-All_Sections_and_Membership_Counts.ps1
> +        "Grabbed 'common.ps1' to the directory alongside the executing script"
Fixed it.

2022-03-30 17:05 UTC, AyronJohnson approved these changes

2022-03-30 17:05 UTC, merged