Modified Get-All_SDS_Attributes_NoRosters.ps1 script to have GraphAPI
OfficeDev/O365-EDU-Tools pull request #98
Opened 2022-04-04 15:41 UTC by ddwivedy84

### Related Issue
https://dev.azure.com/1edu/DIP%20Master/_queries/edit/132826/
### Summary
Modified script to have GraphAPI instead of ADAL cmdlets

### Reason
Old scripts some functionality was not working 

### Proposed Change(s)
ADAL cmdlets to GraphAPI

### Details
_Detailed description of the change(s)_

### Additional Info
_Any additional information or context_

### References
[Example](www.microsoft.com)

### Checklist
- [ ] Documentation

2022-04-04 18:36 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes_NoRosters.ps1
> +    This script is designed to get all SDS objects and attributes, except for Rostering. The result is only 4 CSV files in a trimmed down version of the standard SDS format, as detailed on the page h
Remove spacing.

2022-04-04 18:40 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes_NoRosters.ps1
> +            "State ID" = $au.extension_fe2174665583431c953114ff7268b7b3_Education_StateId
These fields were not in orginal script.  I would leave them out.

2022-04-04 18:54 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes_NoRosters.ps1
>  function Get-SdsSection
Get-SdsSection and Get-Section don't look updated

2022-04-04 19:25 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes_NoRosters.ps1
NIT: Remove spaces before new lines codes

2022-04-04 19:36 UTC, AyronJohnson requested changes
See comments.  Highlights are a few functions not using send-webrequest and old uri (they don't look updated) and extra fields not inlcuded in original script.  Otherwise minor fixes.

2022-04-05 14:51 UTC, ddwivedy84 commented on SDS Scripts/Get-All_SDS_Attributes_NoRosters.ps1
> +            "State ID" = $au.extension_fe2174665583431c953114ff7268b7b3_Education_StateId
Updated to have fields that were in the original script.

2022-04-05 14:52 UTC, ddwivedy84 commented on SDS Scripts/Get-All_SDS_Attributes_NoRosters.ps1
>      $fileName = $eduObjSchool.ToLower() + $(if ($AppendTenantIdToFileName) { "-" + $authToken.TenantId } else { "" }) +".csv"
Updated as suggested

2022-04-05 16:06 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes_NoRosters.ps1
> +$tenantInfo = Get-MgOrganization
I think you need to call these lines after initialize

2022-04-05 17:44 UTC, ddwivedy84 commented on SDS Scripts/Get-All_SDS_Attributes_NoRosters.ps1
> +$tenantInfo = Get-MgOrganization
done

2022-04-05 17:53 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes_NoRosters.ps1
> +	        "ObjectID" = $user.objectID
This is not populating

2022-04-05 17:53 UTC, AyronJohnson commented on SDS Scripts/Get-All_SDS_Attributes_NoRosters.ps1
> +	        "ObjectID" = $user.ObjectID
Not populating.  Maybe change to $user.Id

2022-04-05 18:11 UTC, ddwivedy84 commented on SDS Scripts/Get-All_SDS_Attributes_NoRosters.ps1
> +	        "ObjectID" = $user.objectID
Changed from ObjectID to id. Its populating now.please check

2022-04-05 18:25 UTC, merged