- updated Get-SectionUsageReport scirpt using graphAPI
OfficeDev/O365-EDU-Tools pull request #99
Opened 2022-04-06 07:45 UTC by mss-sivas

### Related Issue
_Please put the related issue number to reference if applicable_  

### Summary
_Brief description of what was changed_

### Reason
_Why is this change being proposed?_

### Proposed Change(s)
- change 1
- change 2
- change N

### Details
_Detailed description of the change(s)_

### Additional Info
_Any additional information or context_

### References
[Example](www.microsoft.com)

### Checklist
- [ ] Documentation

2022-04-06 13:49 UTC, AyronJohnson commented on SDS Scripts/Get-SectionUsageReport.ps1
> +    #Parameter to specify whether to download the script with common functions or not
Since you are notating parameters in the header, move this comment there.

2022-04-06 13:51 UTC, AyronJohnson commented on SDS Scripts/Get-SectionUsageReport.ps1
> +    [string] $OutFolder = ".\Section_Usage_Report",
NIT: Make sure variables have consistent casing format

2022-04-06 14:10 UTC, AyronJohnson commented on SDS Scripts/Get-SectionUsageReport.ps1
>  # Azure enviroment variables
misspelled environment

2022-04-06 14:11 UTC, AyronJohnson commented on SDS Scripts/Get-SectionUsageReport.ps1
> +    Write-Message "Creating output folder path"
This is generating an error for me.  Try Write-Output

2022-04-06 14:33 UTC, AyronJohnson commented on SDS Scripts/Get-SectionUsageReport.ps1
> +$graphScopes = "GroupMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All, Directory.AccessAsUser.All"
I'm not sure GroupMember.ReadWrite.All is needed.  Can script be run without it?  If so please remove from scope and adjust the comment in the top header.

2022-04-06 14:36 UTC, AyronJohnson commented on SDS Scripts/Get-SectionUsageReport.ps1
> +    Write-Message "microsoft authentication"
Reword to "Authenticated to Microsoft"

2022-04-08 09:11 UTC, mss-sivas commented on SDS Scripts/Get-SectionUsageReport.ps1
> +    #Parameter to specify whether to download the script with common functions or not
comment moved to header part

2022-04-08 09:12 UTC, mss-sivas commented on SDS Scripts/Get-SectionUsageReport.ps1
> +    [string] $OutFolder = ".\Section_Usage_Report",
Variable name changed into standard format

2022-04-08 09:12 UTC, mss-sivas commented on SDS Scripts/Get-SectionUsageReport.ps1
>  # Azure enviroment variables
corrected

2022-04-08 09:12 UTC, mss-sivas commented on SDS Scripts/Get-SectionUsageReport.ps1
> +    Write-Message "Creating output folder path"
Changed to Write-Host as suggested

2022-04-08 09:13 UTC, mss-sivas commented on SDS Scripts/Get-SectionUsageReport.ps1
> +function Get-SectionGroups($graphEndPoint, $eduObjectType, $refreshToken, $graphScopes, $logFilePath) {
As suggested, updated the filter code.

2022-04-08 09:14 UTC, mss-sivas commented on SDS Scripts/Get-SectionUsageReport.ps1
> +$graphScopes = "GroupMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All, Directory.AccessAsUser.All"
Yes, script worked after removing the 'GroupMember.ReadWrite.All' variable. Also comment moved to top header.

2022-04-08 09:15 UTC, mss-sivas commented on SDS Scripts/Get-SectionUsageReport.ps1
> +    Write-Message "microsoft authentication"
As suggested, corrected the sentence.

2022-04-08 09:15 UTC, mss-sivas commented on SDS Scripts/Get-SectionUsageReport.ps1
> +$logFilePath = "$OutFolder\SDSSectionUsageReport.log"
Updated the code to use SectionReportLog.

2022-04-08 09:16 UTC, mss-sivas commented on SDS Scripts/Get-SectionUsageReport.ps1
> +    $objectProperties += @{label = "Id"; expression = { $_.id } }, @{label = 'SectionId'; expression = {$_.organizationId}}, @{label = 'Name'; expression = {$_.displayName}}
Replaced with correct attribute in script.

2022-04-08 14:22 UTC, AyronJohnson commented on SDS Scripts/Get-SectionUsageReport.ps1
> +    b. Execute: "connect-graph -scopes GroupMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All, Directory.AccessAsUser.All" to bring up a sign in UI.
GroupMember.ReadWrite.All is no longer used

2022-04-08 14:37 UTC, AyronJohnson requested changes
See new comment

2022-04-08 14:39 UTC, mss-sivas commented on SDS Scripts/Get-SectionUsageReport.ps1
> +    b. Execute: "connect-graph -scopes GroupMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All, Directory.AccessAsUser.All" to bring up a sign in UI.
It is fixed.

2022-04-08 14:42 UTC, AyronJohnson approved these changes

2022-04-08 14:44 UTC, merged